@api-url = http://localhost:3030/boards
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE5ZDE0MzE5NjI2NzlhMWQ2ZmE0NTYiLCJlbWFpbCI6Im15bmV3QHRlc3QuY29tIiwibmFtZSI6InRlc3R1c2VyIiwiYm9hcmQiOlsiNjUxNmY2NzY2ODJlNDkyMzkxZTUwNGZhIiwiNjUxNmY2NzY2ODJlNDkyMzkxZTUwNGZhIl0sImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk2MTkwODAwfQ.3FURAvSkntJIhyLwxeqtmtacLqKTdeHqzZmJHby3nMg


### Test1 6516f65f682e492391e504f8
### Test2 6516f676682e492391e504fa



### GET user boards
GET {{api-url}}/user/6516d9e045a25c72f1ec3824
Authorization: Bearer {{token}}

### GET board with boardId
GET {{api-url}}/6519c5198380c422bd05878e
Authorization: Bearer {{token}}


### Create a board
POST {{api-url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "newTestBoard"
}


### Patch board
# Add id for specific board
PATCH {{api-url}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
   
}