@api-url = http://localhost:3030/boards
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE2ZDllMDQ1YTI1YzcyZjFlYzM4MjQiLCJlbWFpbCI6InRlc3QyMzExMTExMTExMTExMTFAdGVzdC5jb20iLCJuYW1lIjoidGVzdCIsImJvYXJkIjpbInRlc3QxIiwidGVzdDIiXSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2OTYwMDI1NTZ9.orPmvVZyN9C1dVpOzQBZYClVWsVCR5ER0BBnBLN1rgs


### Test1 6516f65f682e492391e504f8
### Test2 6516f676682e492391e504fa



### GET user boards
GET {{api-url}}/6515d740b578cff66fd14cd0
Authorization: Bearer {{token}}


### Create a board
POST {{api-url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Test2"
}


### Patch board
# Add id for specific board
PATCH {{api-url}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
   
}