@api-url = http://localhost:3030/boards
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE1NjA4MjQ5Njk1ZTBmY2M4YjdiMzkiLCJlbWFpbCI6InRlc3QxMjMxMjM0QHRlc3QuY29tIiwibmFtZSI6InRlc3QiLCJib2FyZCI6WyJ0ZXN0MSIsInRlc3QyIl0sImV4cGlyZXNJbiI6IjFkIiwiaWF0IjoxNjk1ODk5Nzg0fQ.UYxXWUL87-U7qEXfH931i9AKoGlP6NDHsb1I3Ki97lw






### GET user boards
GET {{api-url}}
Authorization: Bearer {{token}}


### Create a board
POST {{api-url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Testboard1"
}