@api-url = http://localhost:3030/posts
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE3NDRjNTU5MzExMjk4NmNmNzczOWYiLCJlbWFpbCI6InBvc3RUZXN0ZXJAdGVzdC5jb20iLCJuYW1lIjoidGVzdCIsImJvYXJkIjpbIjY1MTZmNjc2NjgyZTQ5MjM5MWU1MDRmYSIsIjY1MTZmNjc2NjgyZTQ5MjM5MWU1MDRmYSJdLCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTY5NjAyMzc3N30.beMT0Gtjhf9hUqGmwd3UJKjjJUi9fxLjMk9tGw6gNXs


### post a new post
POST {{api-url}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "test post ding dong",
    "content": "Testing testing testing"
}

### Patch a post. You can leave empty fields, they will not be updated (stays with the same value as in database)
PATCH {{api-url}}/6517ddc13d35b8e9ea4eff07
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "update test test test test"
}



### Delete a post
DELETE {{api-url}}/6517459d917578678c13b44f
Authorization: Bearer {{token}}

