@api-url = http://localhost:3030/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTEzMzg2MTc2NTQ5MzgxMWMxNDVlOGQiLCJlbWFpbCI6InRlc3Q1QHRlc3QuY29tIiwibmFtZSI6InRlc3QiLCJleHBpcmVzSW4iOiIxZCIsImlhdCI6MTY5NTc1OTgwOH0.afnG7Bh8uiShpY_4Q4JcXliS2y4TwdTA_uFi_TJqYJQ

### Create a new user!
POST {{api-url}}
Content-Type: application/json

{
    "email": "test6@test.com",
    "name": "test",
    "board": ["board1", "board2", "board3", "board4", "board5"],
    "password": "testpass"
}

### Login
POST {{api-url}}/login
Content-Type: application/json

{
    "email": "test6@test.com",
    "password": "testpass"
}


