@api-url = http://localhost:3030/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NTE2ZDllMDQ1YTI1YzcyZjFlYzM4MjQiLCJlbWFpbCI6InRlc3QyMzExMTExMTExMTExMTFAdGVzdC5jb20iLCJuYW1lIjoidGVzdCIsImJvYXJkIjpbInRlc3QxIiwidGVzdDIiXSwiZXhwaXJlc0luIjoiMWQiLCJpYXQiOjE2OTYwMDI1NTZ9.orPmvVZyN9C1dVpOzQBZYClVWsVCR5ER0BBnBLN1rgs


### add /userid för för att targeta rätt user
GET {{api-url}}/6515c387c9304acd5abe1e98
Authorization: Bearer {{token}}


### Create a new user!
POST {{api-url}}
Content-Type: application/json

{
    "email": "postTester@test.com",
    "name": "test",
    "password": "testpass",
    "board": ["6516f676682e492391e504fa", "6516f676682e492391e504fa"]
}

### Login
POST {{api-url}}/login
Content-Type: application/json

{
    "email": "postTester@test.com",
    "password": "testpass"
}

### add /userid för för att targeta rätt user
PATCH {{api-url}}/6516d9e045a25c72f1ec3824
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "password": "password123"
}

### add /userid för för att targeta rätt user
DELETE {{api-url}}
Authorization: Bearer {{token}}
